// apps/examples/nuxt/using-vue-query-with-auth/app/components/todos.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';

const { $client } = useNuxtApp();

const { data, suspense } = useQuery($client.queries.todos.getMany.queryOptions());

const remainingTodos = computed(() => data.value?.filter((t) => !t.completed) || []);

onServerPrefetch(async () => {
  await suspense();
});
</script>

<template>
  <p v-if="data?.length === 0" class="text-center text-zinc-400 dark:text-zinc-500">No todos yet. Add one above!</p>

  <ul v-else class="space-y-2">
    <li
      v-for="todo in data"
      :key="todo.id"
      class="flex items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
    >
      <ToggleTodoButton :id="todo.id" :completed="todo.completed" />

      <span :class="['flex-1', todo.completed ? 'text-zinc-400 line-through dark:text-zinc-600' : 'text-zinc-900 dark:text-zinc-50']">
        <div class="flex flex-col">
          <p>{{ todo.value }}</p>
          <p class="text-sm text-zinc-400 dark:text-zinc-600">
            {{ todo.createdAt.toISOString().split('T')[0] }}
          </p>
        </div>
      </span>

      <DeleteTodoButton :id="todo.id" />
    </li>
  </ul>

  <p v-if="data && data?.length > 0" class="mt-4 text-sm text-zinc-400 dark:text-zinc-500">{{ remainingTodos.length }} remaining</p>
</template>

// apps/examples/nextjs/app-router/src/components/todos.tsx
import { toggleTodo, deleteTodo } from '../actions';
import { client } from '../lib/typebase/client/client';
import DeleteTodoInput from './delete-todo-input';
import ToggleTodoInput from './toggle-todo-input';

export default async function Todos() {
  const todos = await client.queries.todos.getMany();

  return (
    <>
      {todos.length === 0 ? (
        <p className="text-center text-zinc-400 dark:text-zinc-500">No todos yet. Add one above!</p>
      ) : (
        <ul className="space-y-2">
          {todos.map((todo) => (
            <li
              key={todo.id}
              className="flex items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
            >
              <form action={toggleTodo}>
                <ToggleTodoInput todo={todo} />
              </form>

              <span className={`flex-1 ${todo.completed ? 'text-zinc-400 line-through dark:text-zinc-600' : 'text-zinc-900 dark:text-zinc-50'}`}>
                <div className="flex flex-col">
                  <p>{todo.value}</p>
                  <p className="text-sm text-zinc-400 dark:text-zinc-600">{todo.createdAt.toISOString().split('T')[0]}</p>
                </div>
              </span>

              <form action={deleteTodo}>
                <DeleteTodoInput id={todo.id} />
              </form>
            </li>
          ))}
        </ul>
      )}

      {todos.length > 0 && <p className="mt-4 text-sm text-zinc-400 dark:text-zinc-500">{todos.filter((t) => !t.completed).length} remaining</p>}
    </>
  );
}
