// apps/examples/svelte-kit/using-svelte-query/src/lib/components/todos-skeleton.svelte
<ul class="space-y-2">
	{#each { length: 5 }, idx}
		<li
			class="flex items-center justify-between gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
		>
			<div class="flex w-full items-center gap-3">
				<div class="h-4 w-4 animate-pulse rounded bg-zinc-200 dark:bg-zinc-700"></div>
				<div
					class="h-4 flex-1 animate-pulse rounded bg-zinc-200 dark:bg-zinc-700"
					style={`max-width: ${50 + ((idx * 17) % 40)}%`}
				></div>
			</div>
			<div class="flex h-9 w-5 items-center justify-center">
				<div class="h-5 w-5 animate-pulse rounded bg-zinc-200 dark:bg-zinc-700"></div>
			</div>
		</li>
	{/each}
</ul>

<p class="mt-4 h-4 w-24 animate-pulse rounded bg-zinc-200 dark:bg-zinc-700"></p>

// apps/examples/expo/app/src/components/todos-skeleton.tsx
import { View, Text } from 'react-native';

export default function TodosSkeleton() {
  return (
    <>
      <Text className="mb-4 h-4 w-24 rounded bg-zinc-200 animate-pulse" />

      <View className="gap-2 w-full">
        {Array.from({ length: 5 }).map((_, idx) => (
          <View key={idx} className="flex-row items-center justify-between gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3">
            <View className="flex-row items-center gap-3">
              <View className="h-4 w-4 rounded bg-zinc-200 animate-pulse" />
              <View className="h-4 flex-1 rounded bg-zinc-200 animate-pulse" style={{ maxWidth: `${40 + ((idx * 17) % 40)}%` }} />
            </View>

            <View className="h-9 w-5 flex-row items-center justify-center">
              <View className="h-5 w-5 rounded bg-zinc-200 animate-pulse" />
            </View>
          </View>
        ))}
      </View>
    </>
  );
}
