// apps/examples/svelte-kit/using-svelte-query/src/lib/components/todos.svelte
<script lang="ts">
	import { client } from '$lib/typebase/client/client';
	import { createMutation, getQueryClientContext } from '@tanstack/svelte-query';

	const {
		todos
	}: {
		todos: { id: number; value: string; completed: boolean; createdAt: Date }[];
	} = $props();

	const queryClient = getQueryClientContext();
	const remainingTodos = $derived(todos.filter((t) => !t.completed));

	const toggleTodo = createMutation(() =>
		client.mutations.todos.toggle.mutationOptions({
			onSuccess: async () => {
				await queryClient.refetchQueries({
					queryKey: client.queries.todos.key()
				});
			}
		})
	);

	const deleteTodo = createMutation(() =>
		client.mutations.todos.deleteTodo.mutationOptions({
			onSuccess: async () => {
				await queryClient.refetchQueries({
					queryKey: client.queries.todos.key()
				});
			}
		})
	);
</script>

{#if todos.length === 0}
	<p class="text-center text-zinc-400 dark:text-zinc-500">No todos yet. Add one above!</p>
{:else}
	<ul class="space-y-2">
		{#each todos as todo (`${todo.id}-${todo.completed}`)}
			<li
				class="flex items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
			>
				<button
					type="button"
					disabled={toggleTodo.isPending && toggleTodo.variables.id === todo.id}
					class="flex items-center justify-center enabled:cursor-pointer"
					aria-label="toggle todo"
					onclick={() => toggleTodo.mutate({ id: todo.id })}
				>
					<input
						type="checkbox"
						disabled={toggleTodo.isPending && toggleTodo.variables.id === todo.id}
						checked={todo.completed}
						readOnly
						tabIndex={-1}
						class="pointer-events-none h-4 w-4 accent-zinc-900 disabled:opacity-50 dark:accent-zinc-50"
					/>
				</button>

				<span
					class={`flex-1 ${todo.completed ? 'text-zinc-400 line-through dark:text-zinc-600' : 'text-zinc-900 dark:text-zinc-50'}`}
				>
					<div class="flex flex-col">
						<p>{todo.value}</p>
						<p class="text-sm text-zinc-400 dark:text-zinc-600">
							{todo.createdAt.toISOString().split('T')[0]}
						</p>
					</div>
				</span>

				<button
					type="button"
					disabled={deleteTodo.isPending && deleteTodo.variables.id === todo.id}
					class="text-xl text-zinc-400 enabled:cursor-pointer dark:text-zinc-500"
					onclick={() => deleteTodo.mutate({ id: todo.id })}
				>
					{deleteTodo.isPending && deleteTodo.variables.id === todo.id ? '⏳' : '❌'}
				</button>
			</li>
		{/each}
	</ul>
{/if}

{#if todos.length > 0}
	<p class="mt-4 text-sm text-zinc-400 dark:text-zinc-500">
		{remainingTodos.length} remaining
	</p>
{/if}

// apps/examples/expo/app/src/components/todos.tsx
import { Button, Text, View } from 'react-native';
import { Checkbox } from 'expo-checkbox';
import { useMutation } from '@tanstack/react-query';

import { client } from '../lib/typebase/client/client';
import { queryClient } from '../lib/tanstack-query/query-client';

export default function Todos({ todos }: { todos: { id: number; value: string; completed: boolean; createdAt: Date }[] }) {
  const toggleTodo = useMutation(
    client.mutations.todos.toggle.mutationOptions({
      onSuccess: async () => {
        await queryClient.invalidateQueries({
          queryKey: client.queries.todos.key(),
        });
      },
    })
  );

  const deleteTodo = useMutation(
    client.mutations.todos.deleteTodo.mutationOptions({
      onSuccess: async () => {
        await queryClient.invalidateQueries({
          queryKey: client.queries.todos.key(),
        });
      },
    })
  );

  return (
    <>
      <Text className="mb-4 text-sm text-zinc-400">{todos.filter((t) => !t.completed).length} remaining</Text>

      {todos.length === 0 ? (
        <Text className="text-center text-zinc-400 w-full">No todos yet. Add one above!</Text>
      ) : (
        <View className="gap-2 w-full">
          {todos.map((todo) => (
            <View key={todo.id} className="flex-row items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3">
              <Checkbox
                className="h-4 w-4 accent-zinc-900 disabled:opacity-50"
                value={todo.completed}
                disabled={toggleTodo.isPending && toggleTodo.variables.id === todo.id}
                onValueChange={() => toggleTodo.mutate({ id: todo.id })}
              />

              <View className="flex-1">
                <View>
                  <Text>{todo.value}</Text>
                  <Text className="text-sm text-zinc-400">{todo.createdAt.toISOString().split('T')[0]}</Text>
                </View>
              </View>

              <Button
                title={deleteTodo.isPending && deleteTodo.variables.id === todo.id ? '⏳' : '❌'}
                disabled={deleteTodo.isPending && deleteTodo.variables.id === todo.id}
                onPress={() => deleteTodo.mutate({ id: todo.id })}
              />
            </View>
          ))}
        </View>
      )}
    </>
  );
}
