// apps/examples/svelte-kit/remote-functions/src/lib/components/todos.svelte
<script lang="ts">
	import { deleteTodo, toggleTodo } from '../../routes/actions.remote';

	const {
		todos
	}: {
		todos: { id: number; value: string; completed: boolean; createdAt: Date }[];
	} = $props();

	const remainingTodos = $derived(todos.filter((t) => !t.completed));
</script>

{#if todos.length === 0}
	<p class="text-center text-zinc-400 dark:text-zinc-500">No todos yet. Add one above!</p>
{:else}
	<ul class="space-y-2">
		{#each todos as todo (`${todo.id}-${todo.completed}`)}
			{@const toggle = toggleTodo.for(todo.id)}
			{@const deleteTodoAction = deleteTodo.for(todo.id)}

			<li
				class="flex items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
			>
				<form {...toggle}>
					<input {...toggle.fields.id.as('number', todo.id)} type="hidden" />
					<button
						type="submit"
						disabled={toggle.pending !== 0}
						class="flex items-center justify-center enabled:cursor-pointer"
						aria-label="toggle todo"
					>
						<input
							type="checkbox"
							disabled={toggle.pending !== 0}
							checked={todo.completed}
							readOnly
							tabIndex={-1}
							class="pointer-events-none h-4 w-4 accent-zinc-900 disabled:opacity-50 dark:accent-zinc-50"
						/>
					</button>
				</form>

				<span
					class={`flex-1 ${todo.completed ? 'text-zinc-400 line-through dark:text-zinc-600' : 'text-zinc-900 dark:text-zinc-50'}`}
				>
					<div class="flex flex-col">
						<p>{todo.value}</p>
						<p class="text-sm text-zinc-400 dark:text-zinc-600">
							{todo.createdAt.toISOString().split('T')[0]}
						</p>
					</div>
				</span>

				<form {...deleteTodoAction}>
					<input {...deleteTodoAction.fields.id.as('number', todo.id)} type="hidden" />
					<button
						type="submit"
						disabled={deleteTodoAction.pending !== 0}
						class="text-xl text-zinc-400 enabled:cursor-pointer dark:text-zinc-500"
					>
						{deleteTodoAction.pending !== 0 ? '⏳' : '❌'}
					</button>
				</form>
			</li>
		{/each}
	</ul>
{/if}

{#if todos.length > 0}
	<p class="mt-4 text-sm text-zinc-400 dark:text-zinc-500">
		{remainingTodos.length} remaining
	</p>
{/if}

// apps/examples/nextjs/using-react-query-with-auth/src/components/todos.tsx
'use client';

import { useMutation, useSuspenseQuery } from '@tanstack/react-query';
import { client } from '../lib/typebase/client/client';

export default function Todos() {
  const { data: todos, refetch } = useSuspenseQuery(client.queries.todos.getMany.queryOptions());

  const toggleTodo = useMutation(
    client.mutations.todos.toggle.mutationOptions({
      onSuccess: async () => {
        await refetch();
      },
    })
  );

  const deleteTodo = useMutation(
    client.mutations.todos.deleteTodo.mutationOptions({
      onSuccess: async () => {
        await refetch();
      },
    })
  );

  return (
    <>
      {todos.length === 0 ? (
        <p className="text-center text-zinc-400 dark:text-zinc-500">No todos yet. Add one above!</p>
      ) : (
        <ul className="space-y-2">
          {todos.map((todo) => (
            <li
              key={todo.id}
              className="flex items-center gap-3 rounded-lg border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900"
            >
              <button
                type="button"
                disabled={toggleTodo.isPending && toggleTodo.variables.id === todo.id}
                className="items-center justify-center flex enabled:cursor-pointer"
                onClick={() => toggleTodo.mutate({ id: todo.id })}
              >
                <input
                  key={String(todo.completed)}
                  type="checkbox"
                  disabled={toggleTodo.isPending && toggleTodo.variables.id === todo.id}
                  checked={todo.completed}
                  readOnly
                  tabIndex={-1}
                  className="h-4 w-4 accent-zinc-900 dark:accent-zinc-50 pointer-events-none disabled:opacity-50"
                />
              </button>

              <span className={`flex-1 ${todo.completed ? 'text-zinc-400 line-through dark:text-zinc-600' : 'text-zinc-900 dark:text-zinc-50'}`}>
                <div className="flex flex-col">
                  <p>{todo.value}</p>
                  <p className="text-sm text-zinc-400 dark:text-zinc-600">{todo.createdAt.toISOString().split('T')[0]}</p>
                </div>
              </span>

              <button
                type="button"
                disabled={deleteTodo.isPending && deleteTodo.variables.id === todo.id}
                className="text-zinc-400 dark:text-zinc-500 text-xl enabled:cursor-pointer"
                onClick={() => deleteTodo.mutate({ id: todo.id })}
              >
                {deleteTodo.isPending && deleteTodo.variables.id === todo.id ? '⏳' : '❌'}
              </button>
            </li>
          ))}
        </ul>
      )}

      {todos.length > 0 && <p className="mt-4 text-sm text-zinc-400 dark:text-zinc-500">{todos.filter((t) => !t.completed).length} remaining</p>}
    </>
  );
}
